BEGIN;

SET search_path TO nis2, public;

CREATE TABLE azienda (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice_acn          VARCHAR(50) NOT NULL UNIQUE,
    ragione_sociale     VARCHAR(200) NOT NULL,
    partita_iva         VARCHAR(20) UNIQUE,
    settore             VARCHAR(120) NOT NULL,
    tipologia_soggetto  VARCHAR(20) NOT NULL
        CHECK (tipologia_soggetto IN ('ESSENZIALE', 'IMPORTANTE')),
    pec                 VARCHAR(254),
    attiva              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sede (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id      BIGINT NOT NULL
        REFERENCES azienda(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    codice          VARCHAR(30) NOT NULL,
    denominazione   VARCHAR(150) NOT NULL,
    tipo_sede       VARCHAR(20) NOT NULL
        CHECK (tipo_sede IN ('LEGALE', 'OPERATIVA', 'DATACENTER', 'ALTRO')),
    indirizzo       VARCHAR(200),
    comune          VARCHAR(100),
    provincia       VARCHAR(2),
    nazione         CHAR(2) NOT NULL DEFAULT 'IT',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sede_azienda_codice UNIQUE (azienda_id, codice)
);

CREATE TABLE tipo_asset (
    id              SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice          VARCHAR(30) NOT NULL UNIQUE,
    descrizione     VARCHAR(150) NOT NULL
);

CREATE TABLE asset (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id              BIGINT NOT NULL
        REFERENCES azienda(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    sede_id                 BIGINT
        REFERENCES sede(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    tipo_asset_id           SMALLINT NOT NULL
        REFERENCES tipo_asset(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    codice                  VARCHAR(50) NOT NULL,
    nome                    VARCHAR(150) NOT NULL,
    descrizione             TEXT,
    livello_criticita       VARCHAR(10) NOT NULL
        CHECK (livello_criticita IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA')),
    stato                   VARCHAR(20) NOT NULL DEFAULT 'ATTIVO'
        CHECK (stato IN ('ATTIVO', 'MANUTENZIONE', 'DISMESSO')),
    data_inizio_validita    DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fine_validita      DATE,
    versione                INTEGER NOT NULL DEFAULT 1
        CHECK (versione > 0),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_asset_azienda_codice
        UNIQUE (azienda_id, codice),
    CONSTRAINT uq_asset_id_azienda
        UNIQUE (id, azienda_id),
    CONSTRAINT ck_asset_periodo
        CHECK (
            data_fine_validita IS NULL
            OR data_fine_validita >= data_inizio_validita
        )
);

CREATE TABLE servizio (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id              BIGINT NOT NULL
        REFERENCES azienda(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    codice                  VARCHAR(50) NOT NULL,
    nome                    VARCHAR(150) NOT NULL,
    descrizione             TEXT,
    livello_criticita       VARCHAR(10) NOT NULL
        CHECK (livello_criticita IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA')),
    rto_minuti              INTEGER
        CHECK (rto_minuti IS NULL OR rto_minuti >= 0),
    rpo_minuti              INTEGER
        CHECK (rpo_minuti IS NULL OR rpo_minuti >= 0),
    stato                   VARCHAR(20) NOT NULL DEFAULT 'ATTIVO'
        CHECK (stato IN ('ATTIVO', 'SOSPESO', 'DISMESSO')),
    versione                INTEGER NOT NULL DEFAULT 1
        CHECK (versione > 0),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_servizio_azienda_codice
        UNIQUE (azienda_id, codice),
    CONSTRAINT uq_servizio_id_azienda
        UNIQUE (id, azienda_id)
);

CREATE TABLE asset_servizio (
    azienda_id          BIGINT NOT NULL,
    asset_id            BIGINT NOT NULL,
    servizio_id         BIGINT NOT NULL,
    ruolo_supporto      VARCHAR(20) NOT NULL
        CHECK (ruolo_supporto IN ('PRIMARIO', 'SECONDARIO', 'BACKUP')),
    livello_dipendenza  VARCHAR(10) NOT NULL
        CHECK (livello_dipendenza IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA')),
    note                TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_asset_servizio
        PRIMARY KEY (azienda_id, asset_id, servizio_id),
    CONSTRAINT fk_as_asset
        FOREIGN KEY (asset_id, azienda_id)
        REFERENCES asset(id, azienda_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_as_servizio
        FOREIGN KEY (servizio_id, azienda_id)
        REFERENCES servizio(id, azienda_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE fornitore (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice                  VARCHAR(40) NOT NULL UNIQUE,
    ragione_sociale         VARCHAR(200) NOT NULL,
    identificativo_fiscale  VARCHAR(30) UNIQUE,
    paese                   CHAR(2) NOT NULL DEFAULT 'IT',
    email                   VARCHAR(254),
    telefono                VARCHAR(30),
    attivo                  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dipendenza_fornitore (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id              BIGINT NOT NULL
        REFERENCES azienda(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    fornitore_id            BIGINT NOT NULL
        REFERENCES fornitore(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    asset_id                BIGINT,
    servizio_id             BIGINT,
    tipo_dipendenza         VARCHAR(30) NOT NULL
        CHECK (
            tipo_dipendenza IN (
                'CLOUD',
                'TELECOMUNICAZIONI',
                'SOFTWARE',
                'MANUTENZIONE',
                'BACKUP',
                'DATI',
                'ALTRO'
            )
        ),
    livello_criticita       VARCHAR(10) NOT NULL
        CHECK (livello_criticita IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA')),
    riferimento_contratto   VARCHAR(100),
    data_inizio             DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fine               DATE,
    note                    TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_df_asset
        FOREIGN KEY (asset_id, azienda_id)
        REFERENCES asset(id, azienda_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_df_servizio
        FOREIGN KEY (servizio_id, azienda_id)
        REFERENCES servizio(id, azienda_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_df_target
        CHECK (num_nonnulls(asset_id, servizio_id) >= 1),
    CONSTRAINT ck_df_periodo
        CHECK (
            data_fine IS NULL
            OR data_fine >= data_inizio
        )
);

CREATE TABLE persona (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id      BIGINT NOT NULL
        REFERENCES azienda(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    nome            VARCHAR(80) NOT NULL,
    cognome         VARCHAR(80) NOT NULL,
    email           VARCHAR(254) NOT NULL,
    telefono        VARCHAR(30),
    attiva          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_persona_azienda_email
        UNIQUE (azienda_id, email),
    CONSTRAINT uq_persona_id_azienda
        UNIQUE (id, azienda_id)
);

CREATE TABLE ruolo (
    id              SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice          VARCHAR(40) NOT NULL UNIQUE,
    descrizione     VARCHAR(150) NOT NULL
);

CREATE TABLE responsabilita (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id          BIGINT NOT NULL
        REFERENCES azienda(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    persona_id          BIGINT NOT NULL,
    ruolo_id            SMALLINT NOT NULL
        REFERENCES ruolo(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    asset_id            BIGINT,
    servizio_id         BIGINT,
    principale          BOOLEAN NOT NULL DEFAULT FALSE,
    data_inizio         DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fine           DATE,
    note                TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resp_persona
        FOREIGN KEY (persona_id, azienda_id)
        REFERENCES persona(id, azienda_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_resp_asset
        FOREIGN KEY (asset_id, azienda_id)
        REFERENCES asset(id, azienda_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_resp_servizio
        FOREIGN KEY (servizio_id, azienda_id)
        REFERENCES servizio(id, azienda_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_resp_ambito
        CHECK (num_nonnulls(asset_id, servizio_id) <= 1),
    CONSTRAINT ck_resp_periodo
        CHECK (
            data_fine IS NULL
            OR data_fine >= data_inizio
        )
);

CREATE TABLE punto_contatto (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id          BIGINT NOT NULL
        REFERENCES azienda(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    persona_id          BIGINT NOT NULL,
    ambito              VARCHAR(30) NOT NULL
        CHECK (
            ambito IN (
                'NIS2',
                'INCIDENT_RESPONSE',
                'TECNICO',
                'AMMINISTRATIVO',
                'ALTRO'
            )
        ),
    principale          BOOLEAN NOT NULL DEFAULT FALSE,
    canale_preferito    VARCHAR(10) NOT NULL DEFAULT 'EMAIL'
        CHECK (canale_preferito IN ('EMAIL', 'TELEFONO', 'PEC')),
    note                TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pc_persona
        FOREIGN KEY (persona_id, azienda_id)
        REFERENCES persona(id, azienda_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT uq_pc_azienda_persona_ambito
        UNIQUE (azienda_id, persona_id, ambito)
);

CREATE TABLE audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabella         VARCHAR(63) NOT NULL,
    record_id       BIGINT,
    operazione      CHAR(1) NOT NULL
        CHECK (operazione IN ('I', 'U', 'D')),
    dati_precedenti JSONB,
    dati_successivi JSONB,
    modificato_il   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificato_da   TEXT NOT NULL DEFAULT CURRENT_USER
);

COMMENT ON TABLE azienda IS 'Organizzazioni soggette agli obblighi NIS2.';
COMMENT ON TABLE asset IS 'Asset tecnologici e informativi appartenenti alle aziende.';
COMMENT ON TABLE servizio IS 'Servizi erogati dalle aziende.';
COMMENT ON TABLE asset_servizio IS 'Relazione molti-a-molti tra asset e servizi.';
COMMENT ON TABLE dipendenza_fornitore IS 'Dipendenze di asset o servizi da soggetti terzi.';
COMMENT ON TABLE responsabilita IS 'Assegnazione di ruoli e responsabilità a persone.';
COMMENT ON TABLE punto_contatto IS 'Punti di contatto ufficiali e tecnici.';
COMMENT ON TABLE audit_log IS 'Registro storico delle modifiche alle entità principali.';

COMMIT;
